#!/usr/bin/env node

// Simple type generator for zigar WASM modules
// Generates minimal TypeScript declarations from JavaScript exports

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function generateTypes() {
  const jsFile = path.join(__dirname, 'dist', 'index.js');
  const dtsFile = path.join(__dirname, 'dist', 'index.d.ts');

  if (!fs.existsSync(jsFile)) {
    console.log('JavaScript file not found, skipping type generation');
    return;
  }

  // Read the JavaScript file and extract exports
  const jsContent = fs.readFileSync(jsFile, 'utf8');

  // Extract function names from export statement
  const exportMatch = jsContent.match(/export\s*\{\s*([^}]+)\s*\}/);
  if (!exportMatch) {
    console.log('Could not find exports in JavaScript file');
    return;
  }

  const exportsStr = exportMatch[1];
  const exportLines = exportsStr.split(',').map(line => line.trim());

  // Parse exports to get function names
  const functions = [];
  for (const line of exportLines) {
    // Match patterns like "v2 as simpleWasmDemo"
    const match = line.match(/\w+\s+as\s+(\w+)/);
    if (match && match[1] !== '__zigar' && match[1] !== 'default') {
      functions.push(match[1]);
    }
  }

  // Generate minimal TypeScript declarations
  let dtsContent = '// Auto-generated TypeScript declarations for zigar WASM module\n';
  dtsContent += '// This file is automatically generated - do not edit manually\n\n';

  // Add interface for zigar objects
  dtsContent += '/**\n';
  dtsContent += ' * Represents a Zig slice ([]const u8) returned by zigar\n';
  dtsContent += ' */\n';
  dtsContent += 'export interface ZigSlice {\n';
  dtsContent += '  /** Access the string representation */\n';
  dtsContent += '  readonly string: string;\n';
  dtsContent += '}\n\n';

  // Add function declarations
  for (const func of functions) {
    dtsContent += '/**\n';
    dtsContent += ` * ${func} function\n`;
    dtsContent += ' */\n';
    dtsContent += `export declare function ${func}(): ZigSlice;\n\n`;
  }

  // Add internal exports
  dtsContent += '/**\n';
  dtsContent += ' * Zigar runtime (internal)\n';
  dtsContent += ' */\n';
  dtsContent += 'export declare const __zigar: any;\n\n';

  // Write the .d.ts file
  fs.writeFileSync(dtsFile, dtsContent, 'utf8');
  console.log(`Generated ${dtsFile} with ${functions.length} functions`);
}

generateTypes();